/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System-wide statistics
         * @description Aggregates document counts, cache footprint, and engine configuration for the admin dashboard. Admin only.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.AdminStats"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Credentials */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api.loginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.authResponse"];
                    };
                };
                /** @description invalid credentials */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.userResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Lookup failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register first admin user
         * @description Only available when no users exist. Creates the first user as admin.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Credentials */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api.registerRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.authResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Registration disabled */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all connectors */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.connectorResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new connector */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Connector config */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api.createConnectorRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_muty_nexus_internal_model.ConnectorConfig"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Name already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a connector by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Connector UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.connectorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        /**
         * Update a connector
         * @description Updates connector config. Masked secret values (****...) are preserved from the existing config.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Connector UUID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Updated config */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api.updateConnectorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_muty_nexus_internal_model.ConnectorConfig"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Name already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a connector */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Connector UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{id}/auth/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Telegram auth code
         * @description Completes Telegram authentication by submitting the code received in the Telegram app.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Connector UUID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Auth code */
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{id}/auth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Telegram authentication
         * @description Initiates the Telegram MTProto auth flow. Sends a code to the user's Telegram app.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Connector UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{id}/avatars/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a cached profile avatar from a connector
         * @description Streams the bytes of a profile photo the connector cached to the binary store (e.g. a Telegram sender's avatar, keyed by their external user ID). Auth-scoped to the connector's visibility; returns 404 (not 403) for connectors the caller can't read, to avoid leaking existence. Emits a private, caches-fine response so the browser reuses the blob across conversation views.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Connector UUID */
                    id: string;
                    /** @description External (source-assigned) identifier whose avatar to fetch */
                    external_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/*": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/*": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/*": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sync run history for a connector
         * @description Returns the most recent sync runs (newest first) for a connector. Used by the Activity timeline tab. Limit is clamped to 1..200 with default 50.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Max rows to return (default 50, max 200) */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Connector UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_muty_nexus_internal_model.SyncRun"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{source_type}/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated chronological browse of a conversation
         * @description Returns Hidden=true per-message documents for a (source_type, conversation_id) pair sorted by created_at ASC. Supports cursor pagination via `before` / `after` RFC3339 timestamps, plus `around=RFC3339` for anchor-seeded opens (returns half the limit older + half newer, centered on the anchor). Chat-like connectors (Telegram today, WhatsApp / Signal / Matrix in the future) plug in by emitting their per-message canonical docs with matching ConversationID.
         */
        get: {
            parameters: {
                query?: {
                    /** @description RFC3339 timestamp — return messages strictly before this time */
                    before?: string;
                    /** @description RFC3339 timestamp — return messages strictly after this time */
                    after?: string;
                    /** @description RFC3339 timestamp — return limit/2 messages before and limit/2 after, centered on this time. Cannot be combined with before/after. */
                    around?: string;
                    /** @description Page size (default 50, max 200) */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Connector source type (e.g. telegram) */
                    source_type: string;
                    /** @description Conversation identifier (e.g. Telegram chat ID) */
                    conversation_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.conversationMessagesResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/by-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up a document by (source_type, source_id)
         * @description Resolves a chunk identified by its canonical per-connector identifiers into a Document. Used by the conversation view to lazy-fetch reply targets whose message falls outside the loaded window — when walking a reply_to relation the frontend only has the target's source identifiers and needs to fetch the full doc. Auth-scoped: returns 404 (not 403) when the doc isn't readable, to avoid leaking existence.
         */
        get: {
            parameters: {
                query: {
                    /** @description Source type (e.g. telegram, imap) */
                    source_type: string;
                    /** @description Source-assigned identifier of the chunk */
                    source_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_muty_nexus_internal_model.Document"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download or preview a document's binary content
         * @description Streams the original bytes of a document. Dispatches to the source connector via the BinaryFetcher capability. Returns 404 if the connector does not support previews or if the user lacks read permission. Use ?download=1 to force an attachment disposition instead of inline rendering.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Set to '1' to force attachment disposition */
                    download?: string;
                };
                header?: never;
                path: {
                    /** @description Document UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve typed relations (attachments, replies, threads) for a document
         * @description Returns the neighbors of a document across all relation types. `outgoing` edges are the ones declared on the doc itself (attachment_of, reply_to, member_of_thread, member_of_window); `incoming` edges are the reverse lookup — other docs that point at this one. Dangling edges (target not in index) are returned with `document: null`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Document UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.relatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List self-identities across connected sources
         * @description Returns the requesting user's external identities on each of their *owned* connectors (shared connectors are skipped — they don't represent "me"). Only connectors that have completed auth and populated `external_id` emit an entry. Chat-like UI uses this to distinguish own messages from others.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.identitiesResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Full re-index
         * @description Recreates the OpenSearch index with the current embedding dimension, clears all sync cursors, and triggers a full sync for all enabled connectors.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search across all indexed documents
         * @description Performs hybrid search (BM25 + vector) if embeddings are enabled, otherwise BM25-only.
         */
        get: {
            parameters: {
                query: {
                    /** @description Search query */
                    q: string;
                    /** @description Max results (default 20) */
                    limit?: number;
                    /** @description Pagination offset */
                    offset?: number;
                    /** @description Filter by source types (comma-separated) */
                    sources?: string;
                    /** @description Filter by source names (comma-separated) */
                    source_names?: string;
                    /** @description Filter by date (YYYY-MM-DD) */
                    date_from?: string;
                    /** @description Filter by date (YYYY-MM-DD) */
                    date_to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_muty_nexus_internal_model.SearchResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/embedding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get embedding settings
         * @description Returns current embedding provider configuration. API keys are masked.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.embeddingSettingsResponse"];
                    };
                };
            };
        };
        /**
         * Update embedding settings
         * @description Updates the embedding provider. If provider or model changes, automatically triggers a full re-index. Masked API keys (****...) are preserved.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Embedding settings */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api.embeddingSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.embeddingSettingsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get search ranking tunables
         * @description Returns the active ranking config — per-source half-life + floor + trust weight, plus the global bonus/trust toggles. Admin only.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.rankingSettings"];
                    };
                };
            };
        };
        /**
         * Update search ranking tunables
         * @description Persists ranking knobs and hot-swaps them into the in-memory config so the next query sees the new values. Unknown source_type keys in any of the per-source maps are rejected with 400. Admin only.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Ranking settings */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api.rankingSettings"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.rankingSettings"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/rerank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get rerank settings
         * @description Returns current reranking provider configuration + the min-score floor. API keys are masked.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.rerankSettingsResponse"];
                    };
                };
            };
        };
        /**
         * Update rerank settings
         * @description Updates the reranking provider + min-score floor. Masked API keys (****...) are preserved. min_score must be in [0,1].
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Rerank settings */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api.rerankSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.rerankSettingsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sync-history retention settings
         * @description Returns the currently-persisted retention policy. Admin only. Reports the hard floor on sweep interval so the UI can surface it as a disabled bound instead of letting the user submit an invalid value.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.retentionSettingsResponse"];
                    };
                };
            };
        };
        /**
         * Update sync-history retention settings
         * @description Validates and persists the three retention keys the sweeper reads every tick. Retention values must be non-negative integers (0 disables the rule). The sweep interval is clamped to the hard floor reported by GET.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Retention settings */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api.retentionSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.retentionSettingsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/retention/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run retention cleanup immediately
         * @description Triggers a one-shot sweep of the sync_runs history using the currently-persisted retention rules. Admin only.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: boolean;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Wipe the entire binary cache
         * @description Deletes every cached blob across all connectors. Admin only. Eager-cached data (Telegram) will be re-populated on next sync only if the upstream media is still available; use with care.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/cache/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Wipe the binary cache for a single connector
         * @description Deletes every cached blob for the connector identified by path ID. Admin only. Safe for lazy-mode connectors — they'll repopulate the cache on next preview. Eager-mode connectors lose cached data that may not be re-fetchable if the upstream source has expired.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Connector UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Binary cache stats per connector
         * @description Returns per-source-type/name aggregates of cached binaries (count, total bytes). Admin only.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"] & {
                            data?: components["schemas"]["github_com_muty_nexus_internal_model.BinaryStoreStats"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active and recent sync jobs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.SyncJob"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Sync all enabled connectors
         * @description Starts async sync jobs for all enabled connectors. Skips connectors that are already syncing.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.SyncJob"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/cursors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete all sync cursors
         * @description Clears all sync cursors, forcing a full re-sync on next trigger.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/cursors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a single connector's sync cursor */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Connector UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a running sync job
         * @description Signals the job's context to cancel. Fire-and-forget: returns 202 immediately. The client learns the terminal state via the SSE progress stream. Idempotent — canceling an already-canceled or completed job returns 202.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream live sync progress across all visible connectors via SSE
         * @description Multiplexed Server-Sent Events stream: one connection pushes SyncJob updates for every job the caller can read. Replaces per-job /sync/{id}/progress. Auth accepts either the standard Authorization header or a sse_token query param (required for browser EventSource, which cannot set headers). Sends a heartbeat comment every 15s to keep reverse proxies from closing the connection.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger sync for a single connector
         * @description Starts an async sync job. Returns immediately with the job state.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Connector UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.SyncJob"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Sync already running */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream sync progress via SSE
         * @description Opens a Server-Sent Events stream that pushes SyncJob updates in real-time. Sends an "event: done" when the job completes.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Connector UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users (admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.userResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new user (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description User details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api.createUserRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.userResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Username taken */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user (admin only) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change user password (admin or self) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User UUID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description New password */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api.changePasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["internal_api.APIResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["internal_api.APIResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "github_com_muty_nexus_internal_model.BinaryStoreStats": {
            count?: number;
            source_name?: string;
            source_type?: string;
            total_size?: number;
        };
        "github_com_muty_nexus_internal_model.ConnectorConfig": {
            config?: {
                [key: string]: unknown;
            };
            created_at?: string;
            enabled?: boolean;
            /**
             * @description ExternalID and ExternalName identify who the Nexus user IS on the
             *     external system this connector represents (e.g. own Telegram user
             *     ID + display name after OAuth). Empty when the connector has no
             *     notion of "self" (filesystem) or hasn't completed auth yet. Used
             *     by the /api/me/identities endpoint to drive self-aware UI.
             */
            external_id?: string;
            external_name?: string;
            id?: string;
            last_run?: string;
            name?: string;
            schedule?: string;
            shared?: boolean;
            type?: string;
            updated_at?: string;
            user_id?: string;
        };
        "github_com_muty_nexus_internal_model.Document": {
            content?: string;
            conversation_id?: string;
            created_at?: string;
            hidden?: boolean;
            id?: string;
            imap_message_id?: string;
            indexed_at?: string;
            metadata?: {
                [key: string]: unknown;
            };
            mime_type?: string;
            relations?: components["schemas"]["github_com_muty_nexus_internal_model.Relation"][];
            size?: number;
            source_id?: string;
            source_name?: string;
            source_type?: string;
            title?: string;
            url?: string;
            visibility?: string;
        };
        "github_com_muty_nexus_internal_model.DocumentHit": {
            content?: string;
            conversation_id?: string;
            created_at?: string;
            headline?: string;
            hidden?: boolean;
            id?: string;
            imap_message_id?: string;
            indexed_at?: string;
            match_avatar_key?: string;
            match_created_at?: string;
            match_message_id?: number;
            match_sender_id?: number;
            match_sender_name?: string;
            /**
             * @description Match* fields pinpoint the specific message inside a
             *     conversation-window document that matched the query. Populated
             *     by the search pipeline when a BM25 highlight can be mapped back
             *     to a message_lines entry (telegram window hits today). Empty
             *     for semantic-only hits and for non-window documents — the
             *     frontend renders a bookended window preview in those cases
             *     instead of a pinpoint message card.
             */
            match_source_id?: string;
            metadata?: {
                [key: string]: unknown;
            };
            mime_type?: string;
            rank?: number;
            /**
             * @description RelatedCount is the total number of relations — outgoing (on this doc's
             *     `relations`) plus incoming (other docs referencing this one). The
             *     frontend uses this to hide the "Related" toggle for docs with nothing
             *     to expand, without triggering an extra /related call per hit.
             */
            related_count?: number;
            relations?: components["schemas"]["github_com_muty_nexus_internal_model.Relation"][];
            score_details?: components["schemas"]["github_com_muty_nexus_internal_model.ScoreDetails"];
            size?: number;
            source_id?: string;
            source_name?: string;
            source_type?: string;
            title?: string;
            url?: string;
            visibility?: string;
        };
        "github_com_muty_nexus_internal_model.Facet": {
            count?: number;
            value?: string;
        };
        "github_com_muty_nexus_internal_model.Relation": {
            target_id?: string;
            target_source_id?: string;
            type?: string;
        };
        "github_com_muty_nexus_internal_model.ScoreDetails": {
            final?: number;
            metadata_bonus?: number;
            recency_factor?: number;
            reranker?: number;
            retrieval?: number;
        };
        "github_com_muty_nexus_internal_model.SearchResult": {
            documents?: components["schemas"]["github_com_muty_nexus_internal_model.DocumentHit"][];
            facets?: {
                [key: string]: components["schemas"]["github_com_muty_nexus_internal_model.Facet"][];
            };
            query?: string;
            total_count?: number;
        };
        "github_com_muty_nexus_internal_model.SyncRun": {
            completed_at?: string;
            connector_id?: string;
            docs_deleted?: number;
            docs_processed?: number;
            docs_total?: number;
            error_message?: string;
            errors?: number;
            id?: string;
            started_at?: string;
            status?: string;
        };
        "internal_api.APIResponse": {
            data?: unknown;
            error?: string;
        };
        "internal_api.AdminEngineStats": {
            dimension?: number;
            enabled?: boolean;
            model?: string;
            provider?: string;
        };
        "internal_api.AdminPerSourceStats": {
            cache_bytes?: number;
            cache_count?: number;
            chunk_count?: number;
            document_count?: number;
            first_indexed_at?: string;
            latest_indexed_at?: string;
            source_name?: string;
            source_type?: string;
        };
        "internal_api.AdminStats": {
            embedding?: components["schemas"]["internal_api.AdminEngineStats"];
            per_source?: components["schemas"]["internal_api.AdminPerSourceStats"][];
            rerank?: components["schemas"]["internal_api.AdminEngineStats"];
            total_chunks?: number;
            total_documents?: number;
            users_count?: number;
        };
        "internal_api.SyncJob": {
            completed_at?: string;
            connector_id?: string;
            connector_name?: string;
            connector_type?: string;
            docs_deleted?: number;
            docs_processed?: number;
            docs_total?: number;
            error?: string;
            errors?: number;
            id?: string;
            started_at?: string;
            /** @description running | completed | failed | canceled */
            status?: string;
        };
        "internal_api.authResponse": {
            token?: string;
            user?: components["schemas"]["internal_api.userResponse"];
        };
        "internal_api.changePasswordRequest": {
            password?: string;
        };
        "internal_api.connectorResponse": {
            config?: {
                [key: string]: unknown;
            };
            created_at?: string;
            enabled?: boolean;
            /**
             * @description ExternalID and ExternalName identify who the Nexus user IS on the
             *     external system this connector represents (e.g. own Telegram user
             *     ID + display name after OAuth). Empty when the connector has no
             *     notion of "self" (filesystem) or hasn't completed auth yet. Used
             *     by the /api/me/identities endpoint to drive self-aware UI.
             */
            external_id?: string;
            external_name?: string;
            id?: string;
            last_run?: string;
            name?: string;
            schedule?: string;
            shared?: boolean;
            status?: string;
            type?: string;
            updated_at?: string;
            user_id?: string;
        };
        "internal_api.conversationMessagesResponse": {
            messages?: components["schemas"]["github_com_muty_nexus_internal_model.Document"][];
            next_after?: string;
            next_before?: string;
        };
        "internal_api.createConnectorRequest": {
            config?: {
                [key: string]: unknown;
            };
            enabled?: boolean;
            name?: string;
            schedule?: string;
            shared?: boolean;
            type?: string;
        };
        "internal_api.createUserRequest": {
            password?: string;
            role?: string;
            username?: string;
        };
        "internal_api.embeddingSettingsRequest": {
            api_key?: string;
            model?: string;
            ollama_url?: string;
            provider?: string;
        };
        "internal_api.embeddingSettingsResponse": {
            api_key?: string;
            model?: string;
            ollama_url?: string;
            provider?: string;
        };
        "internal_api.identitiesResponse": {
            identities?: components["schemas"]["internal_api.identityItem"][];
        };
        "internal_api.identityItem": {
            connector_id?: string;
            external_id?: string;
            external_name?: string;
            has_avatar?: boolean;
            source_name?: string;
            source_type?: string;
        };
        "internal_api.loginRequest": {
            password?: string;
            username?: string;
        };
        "internal_api.rankingSettings": {
            known_source_types?: string[];
            metadata_bonus_enabled?: boolean;
            source_half_life_days?: {
                [key: string]: number;
            };
            source_recency_floor?: {
                [key: string]: number;
            };
            source_trust_enabled?: boolean;
            source_trust_weight?: {
                [key: string]: number;
            };
        };
        "internal_api.registerRequest": {
            password?: string;
            username?: string;
        };
        "internal_api.relatedEdge": {
            document?: components["schemas"]["github_com_muty_nexus_internal_model.Document"];
            relation?: components["schemas"]["github_com_muty_nexus_internal_model.Relation"];
        };
        "internal_api.relatedResponse": {
            incoming?: components["schemas"]["internal_api.relatedEdge"][];
            outgoing?: components["schemas"]["internal_api.relatedEdge"][];
        };
        "internal_api.rerankSettingsRequest": {
            api_key?: string;
            min_score?: number;
            model?: string;
            provider?: string;
        };
        "internal_api.rerankSettingsResponse": {
            api_key?: string;
            /**
             * @description MinScore is the post-rerank floor — docs below this are dropped.
             *     Lives on the Rerank endpoint (rather than on Ranking) because it's
             *     only meaningful when a reranker is configured.
             */
            min_score?: number;
            model?: string;
            provider?: string;
        };
        "internal_api.retentionSettingsRequest": {
            retention_days?: number;
            retention_per_connector?: number;
            sweep_interval_minutes?: number;
        };
        "internal_api.retentionSettingsResponse": {
            min_sweep_interval_minutes?: number;
            retention_days?: number;
            retention_per_connector?: number;
            sweep_interval_minutes?: number;
        };
        "internal_api.updateConnectorRequest": {
            config?: {
                [key: string]: unknown;
            };
            enabled?: boolean;
            name?: string;
            schedule?: string;
            shared?: boolean;
            type?: string;
        };
        "internal_api.userResponse": {
            created_at?: string;
            id?: string;
            role?: string;
            username?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
