/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedConnectorsIndexRouteImport } from './routes/_authenticated/connectors.index'
import { Route as AuthenticatedConnectorsIdRouteImport } from './routes/_authenticated/connectors.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminStatsRouteImport } from './routes/_authenticated/admin/stats'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedConversationsSourceTypeConversationIdRouteImport } from './routes/_authenticated/conversations/$sourceType/$conversationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectorsIndexRoute =
  AuthenticatedConnectorsIndexRouteImport.update({
    id: '/connectors/',
    path: '/connectors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConnectorsIdRoute =
  AuthenticatedConnectorsIdRouteImport.update({
    id: '/connectors/$id',
    path: '/connectors/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminStatsRoute = AuthenticatedAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedConversationsSourceTypeConversationIdRoute =
  AuthenticatedConversationsSourceTypeConversationIdRouteImport.update({
    id: '/conversations/$sourceType/$conversationId',
    path: '/conversations/$sourceType/$conversationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/connectors/$id': typeof AuthenticatedConnectorsIdRoute
  '/connectors/': typeof AuthenticatedConnectorsIndexRoute
  '/conversations/$sourceType/$conversationId': typeof AuthenticatedConversationsSourceTypeConversationIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/connectors/$id': typeof AuthenticatedConnectorsIdRoute
  '/connectors': typeof AuthenticatedConnectorsIndexRoute
  '/conversations/$sourceType/$conversationId': typeof AuthenticatedConversationsSourceTypeConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/connectors/$id': typeof AuthenticatedConnectorsIdRoute
  '/_authenticated/connectors/': typeof AuthenticatedConnectorsIndexRoute
  '/_authenticated/conversations/$sourceType/$conversationId': typeof AuthenticatedConversationsSourceTypeConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/account'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/connectors/$id'
    | '/connectors/'
    | '/conversations/$sourceType/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/account'
    | '/'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/connectors/$id'
    | '/connectors'
    | '/conversations/$sourceType/$conversationId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/_authenticated/'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/stats'
    | '/_authenticated/admin/users'
    | '/_authenticated/connectors/$id'
    | '/_authenticated/connectors/'
    | '/_authenticated/conversations/$sourceType/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connectors/': {
      id: '/_authenticated/connectors/'
      path: '/connectors'
      fullPath: '/connectors/'
      preLoaderRoute: typeof AuthenticatedConnectorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connectors/$id': {
      id: '/_authenticated/connectors/$id'
      path: '/connectors/$id'
      fullPath: '/connectors/$id'
      preLoaderRoute: typeof AuthenticatedConnectorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stats': {
      id: '/_authenticated/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AuthenticatedAdminStatsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/conversations/$sourceType/$conversationId': {
      id: '/_authenticated/conversations/$sourceType/$conversationId'
      path: '/conversations/$sourceType/$conversationId'
      fullPath: '/conversations/$sourceType/$conversationId'
      preLoaderRoute: typeof AuthenticatedConversationsSourceTypeConversationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStatsRoute: typeof AuthenticatedAdminStatsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStatsRoute: AuthenticatedAdminStatsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedConnectorsIdRoute: typeof AuthenticatedConnectorsIdRoute
  AuthenticatedConnectorsIndexRoute: typeof AuthenticatedConnectorsIndexRoute
  AuthenticatedConversationsSourceTypeConversationIdRoute: typeof AuthenticatedConversationsSourceTypeConversationIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedConnectorsIdRoute: AuthenticatedConnectorsIdRoute,
  AuthenticatedConnectorsIndexRoute: AuthenticatedConnectorsIndexRoute,
  AuthenticatedConversationsSourceTypeConversationIdRoute:
    AuthenticatedConversationsSourceTypeConversationIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
